# Generated by Django 5.0.2 on 2024-02-06 23:58

import datetime
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('service_id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=255)),
                ('service_desciption', models.TextField(blank=True)),
                ('service_duration', models.DurationField()),
                ('service_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('service_type', models.CharField(choices=[('LASHES', 'Lashes'), ('NAILS', 'Nails'), ('BROWS', 'Brows')])),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_starttime', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 2, 6, 23, 58, 33, 591435))])),
                ('booking_endtime', models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2024, 2, 6, 23, 58, 33, 591449))])),
                ('booking_duration', models.DurationField()),
                ('booking_notes', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('booking_cancelled', models.BooleanField(default=False)),
                ('booking_completed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.services')),
            ],
        ),
    ]
